spring:
  application:
    name: data
  mvc:
    static-path-pattern: /**
  redis:
    host: 10.4.82.184
    port: 31946
    database: 3
  session:
    redis:
      namespace: data:session
    store-type: redis
server:
  port: 8888


